---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pgadmin
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: pgadmin
  components:
    - ../../../../components/openebs
  dependsOn:
    - name: cloudnative-pg
  interval: 30m
  path: ./kubernetes/apps/dbms/pgadmin/app
  postBuild:
    substitute:
      APP: pgadmin
      OPENEBS_CAPACITY: 5Gi
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: dbms
  timeout: 5m
  wait: false
