---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

components:
  - ../../components/common

resources:
  - ./namespace.yaml
  - ./cilium/ks.yaml
  - ./coredns/ks.yaml
  - ./metrics-server/ks.yaml
  - ./reloader/ks.yaml
  - ./external-secrets/ks.yaml
  - ./onepassword/ks.yaml
  - ./spegel/ks.yaml
  - ./intel-gpu-resource-driver/ks.yaml
#  - ./node-feature-discovery/ks.yaml


