---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
components:
  - ../../components/common
resources:
  - ./cilium/ks.yaml
  - ./coredns/ks.yaml
  - ./external-secrets/ks.yaml
  - ./intel-gpu-resource-driver/ks.yaml
  - ./metrics-server/ks.yaml
  - ./namespace.yaml
  - ./onepassword/ks.yaml
  - ./reloader/ks.yaml
  - ./spegel/ks.yaml
  - ./generic-device-plugin/ks.yaml
  - ./node-feature-discovery/ks.yaml
