---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin
  namespace: dbms
spec:
  dataFrom:
    - extract:
        key: pgadmin
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: pgadmin-secret
    template:
      data:
        PGADMIN_DEFAULT_EMAIL: "{{ .PGADMIN_EMAIL }}"
        PGADMIN_DEFAULT_PASSWORD: "{{ .PGADMIN_PASSWORD }}"
        email: "{{ .PGADMIN_EMAIL }}"
        password: "{{ .PGADMIN_PASSWORD }}"
