---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword
  namespace: kube-system
spec:
  provider:
    onepassword:
      auth:
        secretRef:
          connectTokenSecretRef:
            key: token
            name: onepassword-secret
            namespace: kube-system
      connectHost: http://onepassword-connect.kube-system.svc.cluster.local:8080
      vaults:
        Homelab: 1
