apiVersion: v1
kind: Secret
metadata:
  name: onepassword-secret
  namespace: kube-system
stringData:
  1password-credentials.json:
    verifier:
      salt: ENC[AES256_GCM,data:YKqdToCfhw8OD/F9DIOUJzLmKuPLug==,iv:mhRJyc0iN9VEAAhyqOV5QioutjVqEPj9+S9wNrQgkSo=,tag:vM3CkeUByi9149VelNk5sw==,type:str]
      localHash: ENC[AES256_GCM,data:vEhaCyeg8GC4ELwwo0vs3CYTvuiTE9HJb378utOSvODBQfz0nhJn7a6qXA==,iv:dDJPJ4G6bFHae3rmp8TRZIQcJUmyLnxHUA0ZaA2G8gs=,tag:5fHyKb4eECaJ92sLRyaGoA==,type:str]
    encCredentials:
      kid: ENC[AES256_GCM,data:0YHclXBejZ6pfUu2dQf7to8=,iv:nHg7GxMjkarvAtgxmAdAnwiaKeDqfCTz9UxMt8K5wuI=,tag:DYkgnIiQ7+74BOQsCWACWA==,type:str]
      enc: ENC[AES256_GCM,data:7YJTA+AWNQ==,iv:bx42Wc1T8O2cfTCCFZjv9OyTjgcatD8BohSPQThmDps=,tag:4bSY2c/e44REm18RznAMtQ==,type:str]
      cty: ENC[AES256_GCM,data:RW5zu11ucHj65A8=,iv:okyygPYXRDLsrZ0ebam3G4bGlxw76oIVMj6Hn4rhc2o=,tag:vbnSm2WumxSidJXl2xSijg==,type:str]
      iv: ENC[AES256_GCM,data:1E/u5oih72qtwvuUgiwYEw==,iv:Tp9RQ8znxfMNteU1C3V5iCFgRKB/7Npcqk+RtCzz5Cs=,tag:OGJcXJTg9eecfDvNDPsIAA==,type:str]
      data: ENC[AES256_GCM,data:Bz4FkMpWjF6MiI2p2O7zN0XvJ1nORcsFNcCnIsy6gO+P+0c+pL4Mt/Rf3AdQFSBTbhGYPuBNrQdz2CrEZZoxw2mRI7PbnGlWTJT+8qI66kQrFcc1WhK6RNuFZRmEfj7rFPKR9L1TrQj1VfB+lTwnEGeBpq9ftrh+57RLUCwPy6eJIrHqkYt9j5tmeqHlx1p1BNIqBp0ZXml2kapYNqZKjZuHquAFo8Mz2t0BvGB/6Mcjw13vDl4PAwdxTtAoFjWfHkpMZkdUWZYB/4UN1eo9fjGZxxDDoyKRP+Xqg2ia4bHDQIVDycrZNnbQMpeXwkt20jSiZngNbIT/RSXLyTpbzN/5m1FE7kdEnmWPF8RMZP21TvOBYW+wbkZtKTxeab3F9AzpK/Mym5R9AzoMVnyPjra5FGOLvJrhJK40gcf1kHXA1XK+YmJeeHas0/Tha7jvhq00uegOiN7I99uA8NgBm/+CGRu2QUZhNHqJX9OptHwcf5Za7lZnbefHnyEjeRchTqu0DmnJvlHR+J1LM/H1+xN5LaHA6fDHmnvBD41OE+fKqaRYhmR5BSATSNzyVJxVzSnENyn0ocGAwEH1FLWpPSVp/+bhEfXGszg0owNbHI7/z0xAVyRmXlwH2yd9EAZwLZDFbsL7qyape3dQMeqEIidqUZiNGoHete9tdc/pFRTMuI+rsKoULfCmRaG2g1Xmosa3uRT2TgBYUlfpKf1Ls3S/1rbpgKTvlpxKYdGSvTSgO7wVozOqC12PdFTeK6JTUAXvQGO4/R7Cardj8J8vNZgixc0X2ztlKWdBPgOTBf8NN7kaje1o84zfbR3cRHhXOUhs2NbbHcgDqn+V1+qWYrUQ,iv:TPTc0IoKtYaaa35rYWPTEN0YmoByDm2JOE6uQnP407Q=,tag:Xw2spL4OQG+pFRQKRNA7IQ==,type:str]
    version: ENC[AES256_GCM,data:dg==,iv:V7+/c/1VunaQX0SfTSDJbESRewF8/mqp2HEjWCct1k0=,tag:DaBPkaXRnTr0uTpbV+zaCQ==,type:str]
    deviceUuid: ENC[AES256_GCM,data:hLEMT+Yk+SCVryryreb/Tnnx0J9VM7Qe8xM=,iv:+Qo7O4t0y5C1rqemCwI6A+6aEE+0JhG0S1m5dnoQkTU=,tag:7liDuAjet6mIch4W1ITTAw==,type:str]
    uniqueKey:
      alg: ENC[AES256_GCM,data:7WPGazX7Ig==,iv:IjVE3EPzs3hoeJJy2cJ/1pOV37voDRpheuJY1CGJB5k=,tag:5NZ9stVJHuFe84QZMw4jSw==,type:str]
      ext: ENC[AES256_GCM,data:cxAWIw==,iv:GpV3+N+7GrEsNOIRNA5aRm0WTa5p24SvRaWj1Ak4u+c=,tag:Evkd1Tx34NONS4gZJmUo2A==,type:bool]
      k: ENC[AES256_GCM,data:afGki8wxqw8Fc6acn4Xu7TWuXc8HKPaaWGLd4yIR7e7je00Uy+vi0GhOXw==,iv:VqbxHTqhMLyB96AAcJ7etiJ/YhQ9aNWwq8wt4CdvfXQ=,tag:EIKUfvGYVVkcPIRNZu4X5w==,type:str]
      key_ops:
        - ENC[AES256_GCM,data:Dg5njWpfEw==,iv:paG8w+8qzF//zJJtMPPumAxgYx0crDqdvuTz6Uw2TR4=,tag:aFH6kuKgxjhkwSTECGvr5w==,type:str]
        - ENC[AES256_GCM,data:VS2fn1jbow==,iv:W9A/jz1n5wJaX+dWwba7+deCN09yrn5Qamsg0rBRd10=,tag:DnpoQHIvBczP2GmLK7w8FA==,type:str]
      kty: ENC[AES256_GCM,data:reDI,iv:mBS2b0vlgGfHE1jOPTKMba/j7Jzw6gmUDGwCIT0/Yb8=,tag:QE6MgE313qa05sdeaW3WNw==,type:str]
      kid: ENC[AES256_GCM,data:l+GHBRNP8tTa1PS0+U8wbHl5AQeRhXyqseE=,iv:PNxDnRnz225fexUiYQyQ0tsQ9Yvv8Lfknq1KeQCa9rg=,tag:XfRVeZmHBhvD+lMNuxggzQ==,type:str]
  token: ENC[AES256_GCM,data:LD72s7ol6V7BHpvkn/AkBDXTWF+CKFCbSHblBAmnBdZS6ZnUV9RhiGufXRLUgq0SSPOxhEGl6NLqktzUB/EfGtHoK6kw62a3DSgqhdDT5QXFz2y3rrwrndVR8AUGaGqmogceoko8XJ19+7WIY98cDL4yi/ac4LVPuEuE/M6JVqNsQS5mkhTkXaq3Yab0e2wpy2eByhuIMRvhlBvR62txRwaDzD2ni4+gYfplgwEYld6HO+7Npb9G4AJqrGQCdAEZChCS571kgD9gWPROju0cJ8y973GEWv+83fJrhPm7miz4QTFMdupeGcELqTElSXYxLIyEcF9JpwtqHo9acNJcRIjeiJDSDVUOM/OT06mmUB79OdwbetFS/vA+9XoKUVmFY9hLnOD84DIUEwpWSip2Z17nsQzzOhp+FYrVaN6pCGvL1Z9aI1bcVnD5J0gtw12eWyQGOWTMKQWkquSt2zQttoleWHxRRMsJ8KGSaSYoiXL7KXhhXXJYAIFtn3UO4AhrftykJRjsstk7EFsLcMJ6HOsdtLi73/vZN2Ne2hwUZI7ivS53PqdMBoyck6vQCKn0MlwFU99SY3VSgdVbx3SiFXE/9XnjUCMyI+P/oaDwJz8v+9a9uH1bjJzL7z3yUBithYg2hCPr5EYZTV1Vv1lcFGZdohWiza3tZTWdLgapd5n0knAcUhgtnWGybs0V2ZZyhTNXgYI/jhzEQxODr6DeVgrUsOWFlRGa47bk240sbAVmwYoTf97jK/MmJlDnBzDMJpDwaBRO2MIKBd41utPBQu6NKriAyeDx7gvi1cE2wYys06yXFNQ3LCU55StTnkuTWIhUnseBsEAIHCt50VJut0jh,iv:ohu0knhM9uYCQvsiY7IbnC660o2c2YZ5ISk0dSaw4TA=,tag:RRLNaWvRRqRfX/ZqD5i2pw==,type:str]
sops:
  age:
    - recipient: age1n3ql3mrczyduw5hxwcztsxxllfp7zwc6urxg4q6u20ras3whwuks8nqxvx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtM29EZ2FxQWhadWpkdU5Q
        N1B2TFN0enZ6NkNCN0FTaURjTG9GNkVMQkNnCktXMld6ZkxvdW8zeThEMDAzeWhC
        aFhkUldiQ1dFK2psbjBoR2ZTYjdTalkKLS0tIHVXam5yektYdjRKbFJLdnNTSGtK
        WW9qcysxWk82RE04TkRkL1RQN2tOZXcKiIpOIpkcokrYhw33qrnsn0VN2/7mwNPN
        /YtbjrU4fRt4+EFkPWPZ4qGBMeR04vTHhaAkiH+Zy6sG44EJlXeULw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T01:10:33Z"
  mac: ENC[AES256_GCM,data:DnuRXw9v9PbTIefvtTWxsL2j5uPFh+NlxtwyfHclrMOb5MMCClOIcoiQk9F4lP8XClZ9NX6IE+ZQ2eNt3Dm8NnZMhXc12rqLAxThV7LdXj2aXTIFUd0FHMg7sNgqw/Rjg19H0GdAhG9740DxLG6AZ3hgkkm/T0AYoxqTy6AemeA=,iv:wMiEc+jVIMVcRiFxVpNQ1f+lNZWB+H4u3QODs//Hb2w=,tag:R6RGHl+AUGktWSBHtGzTgQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
