---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: &app calibre-web-automated
spec:
  sourcePVC: *app
  trigger:
    schedule: 0 * * * *
  restic:
    pruneIntervalDays: 14
    repository: calibre-web-automated-secret
    retain:
      hourly: 6
      daily: 5
      weekly: 4
      monthly: 2
      yearly: 1
    copyMethod: Clone