---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflare-dns
spec:
  chartRef:
    kind: OCIRepository
    name: cloudflare-dns
  interval: 1h
  values:
    domainFilters: ["${SECRET_DOMAIN}"]
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            key: api-token
            name: cloudflare-dns-secret
    extraArgs:
      - "--cloudflare-dns-records-per-page=1000"
      - "--cloudflare-proxied"
      - "--crd-source-apiversion=externaldns.k8s.io/v1alpha1"
      - "--crd-source-kind=DNSEndpoint"
      - "--gateway-name=envoy-external"
    fullnameOverride: cloudflare-dns
    podAnnotations:
      secret.reloader.stakater.com/reload: cloudflare-dns-secret
    policy: sync
    provider: cloudflare
    serviceMonitor:
      enabled: true
    sources: ["crd", "gateway-httproute"]
    triggerLoopOnEvent: true
    txtOwnerId: default
    txtPrefix: k8s.
