apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:QHxOqfbpFwtKTCVXvUAoPlM3e0+xylJ/IiA7G7/PeDTaILdznPkiAg==,iv:akA9ZF1KqqAyDVKtw0KO0MEMSyKcpyHhE8UbRy/ei8I=,tag:qIhS0LvfGL+UPmshUUK2oQ==,type:str]
sops:
  age:
    - recipient: age1n3ql3mrczyduw5hxwcztsxxllfp7zwc6urxg4q6u20ras3whwuks8nqxvx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4eDhJTDYrb3VZbkdQR29w
        bGh2Q0xrMS9nNktLMFczeTlZNTN1aVRqWldjCmtRVzhzNmozWWVONEN1WHhSeGVy
        aW4wWXRJTGZlVm1EZlZGaHhyT2ZFaUEKLS0tIFZPSTQxcFJCRWx2Y0NMdzVzcDZl
        ME1VLzBueE1iWWhmKzJTNEwxWlA2VGsKt5htPBVVzT9k0aRImzYCowvSkiPiv1pJ
        L8p+gbNKf/b5RJQXw9Negut8ZmdQViXS8qNCgvFHcGIkeNdldp3zQw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-06T16:23:57Z"
  mac: ENC[AES256_GCM,data:YL8V4RU7Q7CmBx1KIie3t+0Zyjvx/udOcVvSRMulsygyF7uHRMmOkm7nbLxEHOaZjfK/07A6A16pj20wetzbkUdqu+uLHFZWpeKVwztDz9V73HKIC3fCBek3Qal9tZLFmHl2jgq8MMnBccOev81hYknO/SdNGD/ifpWzrEYZNdI=,iv:xUx1CjlkITrlfO3QQSpo4N4Nt3XdEfQjluqdlYJH89I=,tag:2ev5G/CL9fkkmapw6h+ZIQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
