---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.5.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: navidrome
spec:
  chartRef:
    kind: OCIRepository
    name: navidrome
  interval: 30m
  values:
    controllers:
      navidrome:
        containers:
          app:
            env:
              ND_AUTHREQUESTLIMIT: 10
              ND_AUTOIMPORTPLAYLISTS: "false"
              ND_CACHEFOLDER: /cache
              ND_DATAFOLDER: /config
              ND_ENABLEDOWNLOADS: "true"
              ND_ENABLEEXTERNALSERVICES: "true"
              ND_ENABLEINSIGHTSCOLLECTOR: "false"
              ND_ENABLESHARING: "false"
              ND_ENABLETRANSCODINGCANCELLATION: "true"
              ND_ENABLETRANSCODINGCONFIG: "false"
              ND_EXTAUTH_TRUSTEDSOURCES: 10.42.0.0/16
              ND_EXTAUTH_USERHEADER: x-authentik-username
              ND_LASTFM_LANGUAGE: de-DE
              ND_LOGLEVEL: info
              ND_MUSICFOLDER: /music
              ND_PORT: 8080
              ND_SCANNER_PURGEMISSING: always
              ND_SCANNER_SCHEDULE: 0 * * * *
              ND_TRANSCODINGCACHESIZE: 8GB
              TZ: Europe/Berlin
            envFrom:
              - secretRef:
                  name: navidrome-secret
            image:
              repository: ghcr.io/navidrome/navidrome
              tag: 0.60.2@sha256:1b3f9556fc4f70cb1c2d3995543e734bdc90c762c9c6ee9a7c5f6a9745efbc3e
            probes:
              liveness: &probes
                custom: true
                enabled: true
                spec:
                  httpGet:
                    path: /ping
                    port: 8080
              readiness: *probes
            resources:
              limits:
                memory: 300Mi
              requests:
                cpu: 25m
                memory: 128Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
              readOnlyRootFilesystem: false
        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
    persistence:
      cache:
        accessMode: ReadWriteOnce
        size: 10Gi
        storageClass: local-hostpath
        suffix: cache
        type: persistentVolumeClaim
      config:
        accessMode: ReadWriteOnce
        advancedMounts:
          navidrome:
            app:
              - path: /config
                readOnly: false
        size: 5Gi
        storageClass: local-hostpath
        type: persistentVolumeClaim
      music:
        advancedMounts:
          navidrome:
            app:
              - path: /music
                readOnly: true
                subPath: audio
        enabled: true
        path: /media
        server: nas.internal
        type: nfs
    route:
      app:
        annotations:
          gatus.home-operations.com/enabled: "true"
          gethomepage.dev/description: Music Streaming Service
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Media
          gethomepage.dev/icon: navidrome.svg
          gethomepage.dev/name: Navidrome
          gethomepage.dev/widget.salt: "{{`{{HOMEPAGE_VAR_NAVIDROME_SALT}}`}}"
          gethomepage.dev/widget.token: "{{`{{HOMEPAGE_VAR_NAVIDROME_TOKEN}}`}}"
          gethomepage.dev/widget.type: navidrome
          gethomepage.dev/widget.url: http://navidrome.self-hosted:8080
          gethomepage.dev/widget.user: "{{`{{HOMEPAGE_VAR_NAVIDROME_USER}}`}}"
        hostnames: ["music.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: navidrome
                port: 8080
    service:
      app:
        controller: navidrome
        ports:
          http:
            port: 8080
