---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - files:
      - ./resources/config.yaml
    name: litellm-configmap
configurations:
  - ./resources/kustomizeconfig.yaml
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
