apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:PlKgC6AIuOG94oAU9bYgjzuDo+6YpIhlrMLPbTrmv4g=,iv:aI/V/C2OuKUI6ZjSRoPmERmoMT4zHP4TlBd5hkgtKW8=,tag:c7O+Md4PNy+OAIiEpsrD7A==,type:str]
sops:
  age:
    - recipient: age1n3ql3mrczyduw5hxwcztsxxllfp7zwc6urxg4q6u20ras3whwuks8nqxvx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRmJRM3VnWkxsU1Z1OStW
        SVRvMGNyY0xQQnhPNVRocWNxakNtVjVPSTE0CkJNamNqVGV2ZnZSdm5acDluQndI
        VCtFOXlPZEE2NHZwRGJVMkhMb2NtVHMKLS0tIEdCeGtLblVlNStSaGlSNDh2Vy9U
        cnA2RGhCd1d5cjc2N0dSY0NHYzBpSG8Kh9OjGl8+pnjk6wW9X2l1exbTYyqbOnLI
        AGG826bC4r7sTKNNDnkNp38YLNlQ2Q2pu/HilZJo/yf212VKsBKN+w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-06T16:23:57Z"
  mac: ENC[AES256_GCM,data:UkK68ZEuy7DX7spaXcLLIz2IcxIVTH5TL++zU2wwEMc9cxKIhUNqEKuxIRAF2e1Sz8X1Zf0rVUYVPdgrstHTBrXAGKC9/+WOk+wMZaske1Tj1WqNscduzIz3iMWbu4KJuDI/H2NoNLCCGUYjpdA4uE0kr2iIw5hwFI+xolMwHZU=,iv:0mf4vMGqaTda9F/aE8P9hMKtxG/cXRZ7Bls5XaJAEgc=,tag:mowX8x9/TMN9U6U8x6wOyg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
