---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: keycloak-secret
    template:
      data:
        # Keycloak
        KC_BOOTSTRAP_ADMIN_USERNAME: "{{ .KEYCLOAK_ADMIN_USER }}"
        KC_BOOTSTRAP_ADMIN_PASSWORD: "{{ .KEYCLOAK_ADMIN_PASS }}"
        KC_DB_URL: "postgresql://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASS }}@postgres-rw.database/keycloak"
        # Postgres Init
        INIT_POSTGRES_DBNAME: keycloak
        INIT_POSTGRES_HOST: postgres-rw.database
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: keycloak
    - extract:
        key: postgres