---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app keycloak
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      keycloak:
        type: statefulset
        replicas: 1
        rollingUpdate:
          unavailable: 1
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18.1.0@sha256:866f15038ed5185a2b8118821f470bb7ca0df8c4231b8e277446e681ebb1ed84
            envFrom: &envFrom
              - secretRef:
                  name: keycloak-secret
        containers:
          keycloak:
            image:
              repository: quay.io/keycloak/keycloak
              tag: 26.4.7@sha256:9409c59bdfb65dbffa20b11e6f18b8abb9281d480c7ca402f51ed3d5977e6007
            args:
              - start
              - --db
              - postgres
            env:
              TZ: "Europe/Berlin"
              KC_DB: postgres
              KC_HOSTNAME: https://sso.${SECRET_DOMAIN}
              KC_HEALTH_ENABLED: "true"
              KC_METRICS_ENABLED: "true"
              KC_HTTP_ENABLED: "true"
              KC_FEATURES: scripts
              KC_PROXY_HEADERS: xforwarded
              KC_PROXY_TRUSTED_ADDRESSES: "10.43.0.0/16,10.42.0.0/16"
              JAVA_OPTS_APPEND: "-Djgroups.dns.query=keycloak-headless.security.svc.cluster.local"
            envFrom: *envFrom
            ports:
              - name: http
                containerPort: &port 8080
              - name: health
                containerPort: &health 9000
            probes:
              readiness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *health
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              liveness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 512Mi
              limits:
                memory: 4096Mi
    defaultPodOptions:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
    service:
      keycloak:
        controller: keycloak
        ports:
          http:
            port: 80
            targetPort: *port
      headless:
        controller: keycloak
        primary: false
        clusterIP: None
        ports:
          http:
            port: 80
            targetPort: *port
    serviceMonitor:
      app:
        endpoints:
          - port: http
    route:
      keycloak:
        hostnames: ["sso.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: keycloak
                port: 80
    # ingress:
    #   keycloak:
    #     hosts:
    #       - host: keycloak.fern.samoth.eu
    #         paths:
    #           - path: /
    #             service:
    #               identifier: keycloak
    #               port: http

    # networkpolicies:
    #   # Allow Keycloak to communicate with himself
    #   keycloak:
    #     controller: keycloak
    #     policyTypes:
    #       - Ingress
    #       - Egress
    #     rules:
    #       ingress: &rule
    #         - from:
    #           - namespaceSelector:
    #               matchLabels:
    #                 kubernetes.io/metadata.name: infrastructure
    #             podSelector:
    #               matchLabels:
    #                 app.kubernetes.io/instance: keycloak
    #                 app.kubernetes.io/name: keycloak
    #       egress: *rule