---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui
  namespace: default
spec:
  dataFrom:
    - extract:
        key: open-webui
    - extract:
        key: postgres
    - extract:
        key: tavily
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: open-webui-secret
    template:
      data:
        DATABASE_HOST: postgres18.dbms.svc.cluster.local
        DATABASE_NAME: open-webui
        DATABASE_PASSWORD: "{{ .POSTGRES_PASS }}"
        DATABASE_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_DBNAME: open-webui
        INIT_POSTGRES_HOST: postgres18.dbms.svc.cluster.local
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        OAUTH_CLIENT_ID: "{{ .OPENWEBUI_OAUTH_CLIENT_ID }}"
        OAUTH_CLIENT_SECRET: "{{ .OPENWEBUI_OAUTH_CLIENT_SECRET }}"
        OPENID_PROVIDER_URL: "{{ .OPENWEBUI_OPENID_PROVIDER_URL }}"
        TAVILY_API_KEY: "{{ .TAVILY_API_KEY }}"
        WEBUI_SECRET_KEY: "{{ .OPENWEBUI_WEBUI_SECRET_KEY }}"
