---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 1h
  values:
    controllers:
      open-webui:
        containers:
          app:
            env:
              DATABASE_TYPE: postgresql
              DEFAULT_LOCALE: de
              DEFAULT_USER_ROLE: user
              ENABLE_LOGIN_FORM: false
              ENABLE_OAUTH_GROUP_CREATION: true
              ENABLE_OAUTH_GROUP_MANAGEMENT: true
              ENABLE_OAUTH_ROLE_MANAGEMENT: true
              ENABLE_OAUTH_SIGNUP: true
              ENABLE_OLLAMA_API: false
              ENABLE_OPENAI_API: true
              ENABLE_RAG_WEB_SEARCH: true
              ENABLE_SEARCH_QUERY: true
              ENABLE_VERSION_UPDATE_CHECK: false
              ENABLE_WEBSOCKET_SUPPORT: true
              IMAGE_GENERATION_ENGINE: automatic1111
              IMAGE_GENERATION_MODEL: dreamshaper_8
              IMAGE_SIZE: 400x400
              IMAGE_STEPS: 8
              OAUTH_ADMIN_ROLES: admin
              OAUTH_ALLOWED_ROLES: users, admin
              OAUTH_MERGE_ACCOUNTS_BY_EMAIL: true
              OAUTH_PICTURE_CLAIM: avatar
              OAUTH_PROVIDER_NAME: t-node
              OAUTH_ROLES_CLAIM: groups
              OAUTH_SCOPES: openid email profile avatar
              OAUTH_UPDATE_PICTURE_ON_LOGIN: true
              RAG_WEB_SEARCH_ENGINE: tavily
              WEBSOCKET_MANAGER: redis
              WEBSOCKET_REDIS_URL: redis://dragonfly.dbms.svc.cluster.local:6379/6
              WEBUI_URL: https://chat.${SECRET_DOMAIN}
            envFrom: &envFrom
              - secretRef:
                  name: open-webui-secret
            image:
              repository: ghcr.io/open-webui/open-webui
              tag: 0.7.2@sha256:16d9a3615b45f14a0c89f7ad7a3bf151f923ed32c2e68f9204eb17d1ce40774b
            resources:
              limits:
                memory: 2Gi
              requests:
                cpu: 250m
                memory: 1Gi
        initContainers:
          init-db:
            envFrom: *envFrom
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18.1.0@sha256:3c54d39f19fdb82ed5b3f286450e4071133cc6025bd0e25856bc2c522f8fc030
        pod:
          annotations:
            reloader.stakater.com/auto: "true"
        strategy: RollingUpdate
    persistence:
      data:
        accessMode: ReadWriteOnce
        enabled: true
        globalMounts:
          - path: /app/backend/data
        size: 2G
        storageClass: local-hostpath
        type: persistentVolumeClaim
      tmpfs:
        advancedMounts:
          open-webui:
            app:
              - path: /tmp
                subPath: tmp
        type: emptyDir
    route:
      app:
        annotations:
          gethomepage.dev/app: open-webui
          gethomepage.dev/description: Interact with your AI models
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: AI
          gethomepage.dev/icon: sh-open-webui.svg
          gethomepage.dev/name: Open WebUI
        hostnames: ["chat.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: 80
    service:
      app:
        controller: open-webui
        ports:
          http:
            port: 80
            targetPort: 8080
