---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: onepassword-connect
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: onepassword-connect
  dependsOn:
    - name: external-secrets
  healthCheckExprs:
    - apiVersion: external-secrets.io/v1
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      kind: ClusterSecretStore
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: onepassword-connect
      namespace: kube-system
  interval: 1h
  path: ./kubernetes/apps/kube-system/onepassword/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: kube-system
  timeout: 5m
