---
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discord-webhook
spec:
  dataFrom:
    - extract:
        key: discord-webhook
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: discord-webhook-secret
    template:
      data:
        address: "{{ .DISCORD_WEBHOOK_URL }}"
