---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seerr
spec:
  dataFrom:
    - extract:
        key: seerr
    - extract:
        key: postgres
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: seerr-secret
    template:
      data:
        INIT_POSTGRES_DBNAME: "{{ .POSTGRES_DB }}"
        INIT_POSTGRES_HOST: postgres18.dbms.svc.cluster.local
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        DB_HOST: postgres18.dbms.svc.cluster.local
        DB_NAME: "{{ .POSTGRES_DB }}"
        DB_PASS: "{{ .POSTGRES_PASS }}"
        DB_USER: "{{ .POSTGRES_USER }}"
        API_KEY: "{{ .SEERR_API_KEY }}"
