---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secret
spec:
  dataFrom:
    - extract:
        key: authentik
    - extract:
        key: postgres
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    name: authentik-secret
    template:
      data:
        AUTHENTIK_EMAIL__FROM: "{{ .AUTHENTIK_EMAIL_FROM }}"
        # Authentik SMTP
        AUTHENTIK_EMAIL__HOST: smtp.${SECRET_DOMAIN}
        AUTHENTIK_EMAIL__PORT: "25"
        # Authentik DBs
        AUTHENTIK_POSTGRESQL__HOST: postgres18.dbms.svc.cluster.local
        AUTHENTIK_POSTGRESQL__NAME: authentik
        AUTHENTIK_POSTGRESQL__PASSWORD: "{{ .POSTGRES_PASS }}"
        AUTHENTIK_POSTGRESQL__USER: "{{ .POSTGRES_USER }}"
        AUTHENTIK_SECRET_KEY: "{{ .AUTHENTIK_SECRET_KEY }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: authentik
        INIT_POSTGRES_HOST: postgres18.dbms.svc.cluster.local
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
