---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/common
resources:
  - ./namespace.yaml
  - ./echo/ks.yaml
  - ./gitea/ks.yaml
  - ./smtp-relay/ks.yaml
  - ./open-webui/ks.yaml
  - ./sonarr/ks.yaml
  - ./copilot-api/ks.yaml
  - ./calibre-web-automated/ks.yaml
  - ./homepage/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./lidarr/ks.yaml
  - ./plex/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./slskd/ks.yaml