---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/common
resources:
  - ./echo/ks.yaml
  - ./homepage/ks.yaml
  - ./litellm/ks.yaml
  - ./mosquitto/ks.yaml
  - ./namespace.yaml
  - ./smtp-relay/ks.yaml
  - ./zigbee2mqtt/ks.yaml
  - ./home-assistant/ks.yaml