apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:tNs0jVezkqk4wrYV1JAszy5Yg4t7zqFEskcqXcSGrxZ+iVr4Bz7BaUu/LK1n249DgyIj265IOvQfrB33T55oOAZV7SkEGfwUNLi2kNZelVYoHsnTzzL9EOsk2tQK/F/7HB1G5CFaxhHcc/ol01sAK5a+GXCJPlZrdZTxc0cIXy7h+8S+2slJfBMihLwg9T+wVzf2M2JeC5I9kxRs445rqRtbUJxGGcufyE/taTEKQThDWwZ6,iv:21j7lhtsGdV9kiktSghXYhUI4U5R6wgO3XFZWrtuq04=,tag:ESMUIXy5IDCtuAJ9ebDRcw==,type:str]
sops:
  age:
    - recipient: age1n3ql3mrczyduw5hxwcztsxxllfp7zwc6urxg4q6u20ras3whwuks8nqxvx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydFUyVlZndE04VFYxRnB0
        aW9nOEZwWUVPeFg2YU1yZEVoNmEvbWFFZTI0CnNSUXR3OXMxN1JKVWNTeU9rbnNY
        T0N1bTZRamxWZ0szM2Yxd2wvcEJTdlEKLS0tIEZkSFMzbE9tQnkyOVFhZkJRQzZ6
        Q0F3eGg4UW5TUGZpYWkvN2t2OFloRFkKxejV9G+6hTFh17gR+Px26KEhr65MSSZB
        s4jy+ZWka+Y0JFcPXVRweu1bXW582KkFiFIBVUDgfbFoUM7vw70Nug==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-06T16:23:57Z"
  mac: ENC[AES256_GCM,data:llzomSO98KBRCeiWEUYEXoMGH7DcvcIfujBPVVjGJRAXVrTxXYSPxcVDY/9RoNrUWAZw2f4BJKRqFSU9fAN2iA7N4itVjLXFV0LfUN/3JgVQAx/xS0giLQZvoYuCFigH5HMoWZ0HOLl/zy87VukmxX6eAjet2yZRw3wjXIN7D2w=,iv:tSTWV/t+JoB25uUkIQeKAA0ANpmnx6FqnO56/cZQglk=,tag:7nmg7UKRJiB/6N4ilncdaw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
