---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ngx
  namespace: self-hosted
spec:
  dataFrom:
    - extract:
        key: paperless-ngx
    - extract:
        key: postgres
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: paperless-ngx-secret
    template:
      data:
        INIT_POSTGRES_HOST: &host postgres18.dbms.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_DBNAME: "{{ .POSTGRES_DB }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        PAPERLESS_DBHOST: *host
        PAPERLESS_DBPORT: "5432"
        PAPERLESS_DBUSER: "{{ .POSTGRES_USER }}"
        PAPERLESS_DBPASS: "{{ .POSTGRES_PASS }}"
        PAPERLESS_DBNAME: "{{ .POSTGRES_DB }}"
        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: |
          {
            "openid_connect": {
              "APPS": [
                  {
                      "provider_id": "authentik",
                      "name": "Authentik",
                      "client_id": "{{ .PAPERLESS_OAUTH_CLIENT_ID }}",
                      "secret": "{{ .PAPERLESS_OAUTH_CLIENT_SECRET }}",
                      "settings": {
                          "server_url": "{{ .PAPERLESS_OAUTH_SERVER_URL}}",
                          "fetch_userinfo": True,
                      },
                  },
              ]
          }
