---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea
  namespace: default
spec:
  dataFrom:
    - extract:
        key: gitea
    - extract:
        key: postgres
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: gitea-secret
    template:
      data:
        GITEA__database__HOST: &db_host postgres18.dbms.svc.cluster.local
        GITEA__database__NAME: &db_name gitea
        GITEA__database__PASSWD: "{{ .POSTGRES_PASS }}"
        GITEA__database__USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_DBNAME: *db_name
        INIT_POSTGRES_HOST: *db_host
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
