---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres18-secret
  namespace: dbms
spec:
  dataFrom:
    - extract:
        key: s3-storage
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    name: postgres18-secret
    template:
      data:
        AWS_ACCESS_KEY_ID: "{{ .S3_ACCESS_KEY }}"
        AWS_SECRET_ACCESS_KEY: "{{ .S3_SECRET_KEY }}"
      engineVersion: v2
