---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: homelab-backup-store
  namespace: dbms
spec:
  configuration:
    data:
      compression: bzip2
    destinationPath: s3://postgres18/
    endpointURL: https://${S3_BACKUP_ENDPOINT}
    s3Credentials:
      accessKeyId:
        key: AWS_ACCESS_KEY_ID
        name: postgres18-secret
      secretAccessKey:
        key: AWS_SECRET_ACCESS_KEY
        name: postgres18-secret
    wal:
      compression: bzip2
      maxParallel: 4
  retentionPolicy: 30d
