---
apiVersion: v1
kind: Service
metadata:
  name: postgres18
  annotations:
    lbipam.cilium.io/ips: 192.168.178.130
    external-dns.alpha.kubernetes.io/hostname: postgres.${SECRET_DOMAIN}
spec:
  type: LoadBalancer
  selector:
    cnpg.io/cluster: postgres18
    cnpg.io/instanceRole: primary
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432