---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adguard-dns
spec:
  dataFrom:
    - extract:
        key: adguard
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: adguard-dns-secret
    template:
      data:
        ADGUARD_PASSWORD: "{{ .ADGUARD_HOME_PASS }}"
        ADGUARD_URL: "{{ .ADGUARD_HOME_URL }}"
        ADGUARD_USER: "{{ .ADGUARD_HOME_USER }}"
