---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: copilot-api
spec:
  chartRef:
    kind: OCIRepository
    name: copilot-api
  interval: 1h
  values:
    controllers:
      copilot-api:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            env:
              TZ: Europe/Berlin
            envFrom:
              - secretRef:
                  name: copilot-api-secret
            image:
              repository: ghcr.io/ericc-ch/copilot-api
              tag: v0.7@sha256:528117aa62e0393f90dbdb8f33ab0c8383335690c06eeee9c2abc7f81b6d974f
            probes:
              liveness: &ref_0
                custom: true
                enabled: true
                spec:
                  failureThreshold: 3
                  httpGet:
                    path: /
                    port: 4141
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
              readiness: *ref_0
            resources:
              limits:
                memory: 512Mi
              requests:
                cpu: 10m
                memory: 64Mi
        replicas: 1
        strategy: RollingUpdate
    defaultPodOptions:
      securityContext:
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
    persistence:
      config:
        accessMode: ReadWriteOnce
        enabled: true
        globalMounts:
          - path: /.local
        size: 3Gi
        storageClass: local-hostpath
        type: persistentVolumeClaim
    route:
      app:
        hostnames: ["api.ai.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: 4141
    service:
      app:
        ports:
          http:
            port: 4141
