---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: self-hosted
components:
  - ../../components/common
resources:
  - ./atuin/ks.yaml
  - ./bentopdf/ks.yaml
  - ./calibre-web-automated/ks.yaml
  - ./miniflux/ks.yaml
  - ./namespace.yaml
  - ./navidrome/ks.yaml
  - ./openclaw/ks.yaml
  - ./open-webui/ks.yaml
  - ./paperless-ngx/ks.yaml
  - ./youtube-dl/ks.yaml