---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blackbox-exporter-lan
spec:
  chartRef:
    kind: OCIRepository
    name: blackbox-exporter-lan
  interval: 1h
  values:
    config:
      modules:
        http_2xx:
          http:
            follow_redirects: true
            preferred_ip_protocol: ip4
            valid_http_versions:
              - HTTP/1.1
              - HTTP/2.0
          prober: http
          timeout: 5s
        icmp:
          icmp:
            preferred_ip_protocol: ip4
          prober: icmp
          timeout: 5s
        tcp_connect:
          prober: tcp
          tcp:
            preferred_ip_protocol: ip4
          timeout: 5s
    fullnameOverride: blackbox-exporter-lan
    prometheusRule:
      enabled: true
      rules:
        - alert: LanProbeFailed
          annotations:
            summary: The probe targeting {{ $labels.instance }} is currently having connectivity issues
          expr: |-
            probe_success{service="blackbox-exporter-lan"} == 0
          for: 15m
          labels:
            severity: critical
    serviceMonitor:
      enabled: true
      selfMonitor:
        enabled: true
