---
alerting:
  pushover:
    application-token: ${BUDDY_PUSHOVER_TOKEN}
    default-alert:
      description: health-check failed
      failure-threshold: 3
      minimum-reminder-interval: 1h
      send-on-resolved: true
      success-threshold: 2
    priority: 1
    resolved-priority: 0
    title: Gatus
    user-key: ${BUDDY_PUSHOVER_USER_KEY}
endpoints:
  - alerts:
      - type: pushover
    conditions:
      - "[STATUS] == 200"
    group: buddy
    interval: 1m
    name: Status Page
    ui:
      hide-hostname: true
      hide-url: true
    url: https://${BUDDY_STATUS_HOSTNAME}
external-endpoints:
  - alerts:
      - type: pushover
    group: buddy
    heartbeat:
      interval: 5m
    name: Heartbeat
    token: ${BUDDY_HEARTBEAT_TOKEN}
