---
connectivity:
  checker:
    interval: 1m
    target: 1.1.1.1:53
endpoints:
  - conditions:
      - "[CONNECTED] == true"
    group: connectivity
    interval: 1m
    name: Cloudflare
    url: icmp://1.1.1.1
metrics: true
storage:
  caching: true
  path: ${GATUS_CONFIG_PATH}/gatus.db
  type: sqlite
ui:
  buttons:
    - link: https://github.com/charming-byte
      name: Github
    - link: https://github.com/charming-byte/homelab
      name: Homelab
  header: Status
  link: https://github.com/charming-byte
  logo: https://avatars.githubusercontent.com/u/13345912
  title: Status | Gatus
web:
  port: ${GATUS_WEB_PORT}
