apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:o3p3+dXKLfjaaP+jn60LqBxJ05IXIpWqrIORA6qMe290Cc9rTjMs/g==,iv:I+4HYhrBs3dafeP5SLVJQv2/+Jojul28dqaO5ocTJx0=,tag:pO8mfXHbw8YGtCJ2Sl2DCw==,type:str]
sops:
  age:
    - recipient: age1n3ql3mrczyduw5hxwcztsxxllfp7zwc6urxg4q6u20ras3whwuks8nqxvx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySnNvM0RGdDNOWHJZbVFv
        QzZNVW9FdjVmQ1l1VWNnNUdUelBjTjJkTEV3ClNuZmdsK1hKUkJldVJDbThrUXJm
        aVFSWkRqbUFtbWtySlhwNWNTSHp2YmsKLS0tIEwxenRsU1BRM2pEV1NWcjN4aHdy
        YVBuemRqN0V1T2NIdHpoNncwWUtnNE0KPNiGbQU6f5OoxL155bYrzYN8UTnZJzYx
        FjkDBvraIOX0WylvXGHUXhCiFlNCvzNauEpTOpCfn07n5bWV0bviiw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-06T16:23:57Z"
  mac: ENC[AES256_GCM,data:Ez/0lc5Jv9dpny7D1zoxvpse1EuAvEX86ZoqhLVgEKLkRc7jnEbXr7rHb/Xv8Ksi2/ZnoCiL1g1oDYmPduh/DnpqHhoLOf7Osy917+okWVnwmFWh0muX5n40ScpzRE7rUnAqNib4buCwz1XmPshK80wI9MtptT8gxgljHFXkHmI=,iv:QgsTkn2u4jvFo24pSqzinqA6RPLzRn3+2ZHVtzmkRH8=,tag:1n27QTamTTCuUgvCIDvl5g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
