---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: runner-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-hostpath

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: gitea-runner
  name: gitea-runner
spec:
  replicas: 5
  selector:
    matchLabels:
      app: gitea-runner
  strategy: {}
  template:
    metadata:
      labels:
        app: gitea-runner
    spec:
      containers:
        - env:
            - name: GITEA_INSTANCE_URL
              value: http://gitea.default.svc.cluster.local
            - name: GITEA_RUNNER_ACTION_CACHE_DIR
              value: /cache/actions
            - name: ACT_CACHE_SERVER_DIR
              value: /cache/server
            - name: GITEA_RUNNER_JOB_CONTAINER_NETWORK
              value: host
            - name: GITEA_RUNNER_REGISTRATION_TOKEN
              valueFrom:
                secretKeyRef:
                  key: GITEA_RUNNER_REGISTRATION_TOKEN
                  name: gitea-runner-secret
          image: vegardit/gitea-act-runner:dind-0.2.10
          imagePullPolicy: Always
          name: runner
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /data
              name: runner-data
            - mountPath: /cache
              name: runner-cache
      restartPolicy: Always
      securityContext:
        fsGroup: 2000
      volumes:
        - emptyDir: {}
          name: runner-data
        - emptyDir: {}
          name: runner-cache
