---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-runner
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: gitea-runner-secret
    template:
      data:
        # Gitea Runner
        GITEA_RUNNER_REGISTRATION_TOKEN: "{{ .RUNNER_REGISTRATION_TOKEN }}"
  dataFrom:
    - extract:
        key: gitea