---
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: calibre-web-automated
  namespace: self-hosted
spec:
  components:
    - ../../../../components/nfs-scaler
  dependsOn:
    - name: openebs
      namespace: openebs-system
    - name: onepassword-connect
      namespace: kube-system
  interval: 1h
  path: ./kubernetes/apps/self-hosted/calibre-web-automated/app
  postBuild:
    substitute:
      APP: calibre-web-automated
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: self-hosted
  wait: false
