---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux
  namespace: self-hosted
spec:
  dataFrom:
    - extract:
        key: postgres
    - extract:
        key: miniflux
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: miniflux-secret
    template:
      data:
        DATABASE_URL: "user={{ .POSTGRES_USER }} password={{ .POSTGRES_PASS }} dbname=miniflux sslmode=disable host=postgres18.dbms.svc.cluster.local"
        INIT_POSTGRES_DBNAME: miniflux
        INIT_POSTGRES_HOST: postgres18.dbms.svc.cluster.local
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
