---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: soularr
spec:
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: soularr-secret
    template:
      engineVersion: v2
      data:
        LIDARR_API_KEY: "{{ .LIDARR_API_KEY }}"
        SLSKD_API_KEY: "{{ .SLSKD_API_KEY_SOULARR }}"
  dataFrom:
    - extract:
        key: lidarr
    - extract:
        key: slskd
