---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: soularr
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  driftDetection:
    mode: enabled
  install:
    createNamespace: true
    remediation:
      retries: 3
  interval: 1h
  maxHistory: 2
  uninstall:
    keepHistory: false
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    configMaps:
      config:
        data:
          config.ini: |-
            [Lidarr]
            api_key = ${LIDARR_API_KEY}
            host_url = http://lidarr.downloads.svc.cluster.local:8686
            download_dir = /media/downloads/soulseek

            [Slskd]
            api_key = ${SLSKD_API_KEY}
            host_url = http://slskd:80
            url_base = /
            download_dir = /media/downloads/soulseek
            delete_searches = False
            stalled_timeout = 3600

            [Release Settings]
            use_most_common_tracknum = True
            allow_multi_disc = True
            accepted_countries = Europe,Japan,United Kingdom,United States,[Worldwide],Australia,Canada
            accepted_formats = CD,Digital Media,Vinyl

            [Search Settings]
            search_timeout = 5000
            maximum_peer_queue = 50
            minimum_peer_upload_speed = 0
            minimum_filename_match_ratio = 0.5
            allowed_filetypes = flac 24/192,flac 16/44.1,flac,mp3 320,mp3
            search_for_tracks = True
            album_prepend_artist = False
            track_prepend_artist = True
            search_type = incrementing_page
            number_of_albums_to_grab = 10
            remove_wanted_on_failure = False
            search_source = missing

            [Logging]
            level = INFO
            format = [%(levelname)s|%(module)s|L%(lineno)d] %(asctime)s: %(message)s
            datefmt = %Y-%m-%dT%H:%M:%S%z
    controllers:
      soularr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          soularr:
            env:
              SCRIPT_INTERVAL: 300
              TZ: Europe/Berlin
            image:
              repository: mrusse08/soularr
              tag: latest
            resources:
              limits:
                memory: 512Mi
              requests:
                cpu: 100m
                memory: 128Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
              readOnlyRootFilesystem: true
        initContainers:
          config-setup:
            command:
              - "/usr/local/bin/bash"
              - -c
              - |
                envsubst < /tmp/config.ini > /data/config.ini
                exit 0
            envFrom:
              - secretRef:
                  name: soularr-secret
            image:
              repository: ghcr.io/dmfrey/bash
              tag: 5.2.26-alpine3.20
        type: statefulset
    defaultPodOptions:
      labels:
        setGateway: "false"
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
    persistence:
      config-file:
        advancedMounts:
          soularr:
            config-setup:
              - path: /tmp/config.ini
                readOnly: true
                subPath: config.ini
        defaultMode: 0775
        name: config
        type: configMap
      data:
        existingClaim: soularr
      media:
        globalMounts:
          - path: /media/downloads/soulseek
            subPath: downloads/soulseek
        path: /media
        server: nas.internal
        type: nfs
      tmp:
        medium: Memory
        type: emptyDir
    service:
      soularr:
        controller: soularr
        enabled: false
