---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: soularr
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  driftDetection:
    mode: enabled
  install:
    createNamespace: true
    remediation:
      retries: 3
  interval: 1h
  maxHistory: 2
  uninstall:
    keepHistory: false
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      soularr:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          config-setup:
            image:
              repository: ghcr.io/dmfrey/bash
              tag: 5.2.26-alpine3.20
            command:
              - "/usr/local/bin/bash"
              - -c
              - |
                envsubst < /tmp/config.ini > /data/config.ini
                exit 0
            envFrom:
              - secretRef:
                  name: soularr-secret
        containers:
          soularr:
            env:
              SCRIPT_INTERVAL: 300
              TZ: Europe/Berlin
            image:
              repository: mrusse08/soularr
              tag: latest@sha256:84fead20dc2bcc00d6f0d2df53e56866b4fe634640e075820b420ae4ea146fd2
            resources:
              limits:
                memory: 512Mi
              requests:
                cpu: 100m
                memory: 128Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
              readOnlyRootFilesystem: true
        type: statefulset
    defaultPodOptions:
      labels:
        setGateway: "false"
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
    persistence:
      config-secret:
        type: secret
        name: "{{ .Release.Name }}-secret"
        advancedMounts:
          soularr:
            config-setup:
              - path: /tmp/config.ini
                subPath: config.ini
                readOnly: true
      data:
        existingClaim: soularr
        globalMounts:
          - path: /data
      media:
        globalMounts:
          - path: /media/downloads/soulseek
            subPath: downloads/soulseek
        path: /media
        server: nas.internal
        type: nfs
      tmp:
        type: emptyDir
    service:
      soularr:
        controller: soularr
        enabled: false
