---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: miniflux
  namespace: self-hosted
spec:
  components:
    - ../../../../components/ext-auth
  interval: 1h
  path: ./kubernetes/apps/self-hosted/miniflux/app
  postBuild:
    substitute:
      EXT_AUTH_APP: miniflux
      EXT_AUTH_TARGET_NAME: miniflux
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: self-hosted
  wait: false
