---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slskd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: slskd-secret
    template:
      data:
        # slskd
        SLSKD_SLSK_USERNAME: "{{ .SLSKD_SLSK_USERNAME }}"
        SLSKD_SLSK_PASSWORD: "{{ .SLSKD_SLSK_PASSWORD }}"
        # gluetun
        VPN_SERVICE_PROVIDER: "{{ .GLUETUN_VPN_SERVICE_PROVIDER }}"
        PORT_FORWARD_ONLY: "on"
        VPN_PORT_FORWARDING: "on"
        SERVER_COUNTRIES: Netherlands
        VPN_PORT_FORWARDING_LISTENING_PORT: "50429"
        VPN_TYPE: wireguard
        DNS_ADDRESS: 10.2.0.1
        FIREWALL_OUTBOUND_SUBNETS: "192.168.0.0/20,10.42.0.0/16"
        WIREGUARD_ADDRESSES: "{{ .GLUETUN_WIREGUARD_ADDRESSES }}"
        WIREGUARD_PUBLIC_KEY: "{{ .GLUETUN_WIREGUARD_PUBLIC_KEY }}"
        WIREGUARD_PRIVATE_KEY: "{{ .GLUETUN_WIREGUARD_PRIVATE_KEY }}"
  dataFrom:
    - extract:
        key: slskd