# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app gitea
  namespace: &namespace self-hosted
spec:
  interval: 1h
  path: ./kubernetes/apps/self-hosted/gitea/app
  dependsOn:
    - name: onepassword-connect
      namespace: kube-system
    - name: cloudnative-pg-cluster
      namespace: dbms
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: false
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app gitea-runner
  namespace: &namespace self-hosted
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: gitea
  path: ./kubernetes/apps/self-hosted/gitea/runner
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: false
  interval: 1h
  retryInterval: 10m
  timeout: 3m