# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitea
  namespace: self-hosted
spec:
  dependsOn:
    - name: onepassword-connect
      namespace: kube-system
    - name: cloudnative-pg-cluster
      namespace: dbms
  interval: 1h
  path: ./kubernetes/apps/self-hosted/gitea/app
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: self-hosted
  wait: false

# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  labels:
    substitution.flux.home.arpa/enabled: "true"
  name: gitea-runner
  namespace: self-hosted
spec:
  dependsOn:
    - name: gitea
  interval: 1h
  path: ./kubernetes/apps/self-hosted/gitea/runner
  prune: true
  retryInterval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: self-hosted
  timeout: 3m
  wait: false
