# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-superuser
  namespace: database
spec:
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: postgres
      property: POSTGRES_SUPER_USER
  - secretKey: password
    remoteRef:
      key: postgres
      property: POSTGRES_SUPER_PASS
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-pgsql
  namespace: database
spec:
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
  data:
  - secretKey: minio_s3_access_key
    remoteRef:
      key: minio_tf_pgsql
      property: access_key
  - secretKey: minio_s3_secret_key
    remoteRef:
      key: minio_tf_pgsql
      property: secret_key