---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opnsense-dns
spec:
  dataFrom:
    - extract:
        key: opnsense
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: opnsense-dns-secret
    template:
      data:
        OPNSENSE__API_SECRET: "{{ .OPNSENSE__API_SECRET }}"
        OPNSENSE__API_KEY: "{{ .OPNSENSE__API_KEY }}"
