---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: seerr
  namespace: downloads
spec:
  dependsOn:
    - name: openebs
      namespace: openebs-system
    - name: cloudnative-pg-cluster
      namespace: dbms
    - name: onepassword-connect
      namespace: kube-system
  interval: 1h
  path: ./kubernetes/apps/downloads/seerr/app
  postBuild:
    substitute:
      APP: seerr
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: downloads
  wait: false
