---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/keda.sh/scaledobject_v1alpha1.json
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ${APP}
spec:
  advanced:
    restoreToOriginalReplicaCount: true
  cooldownPeriod: 0
  maxReplicaCount: 1
  minReplicaCount: 0
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${APP}
  triggers:
    - metadata:
        ignoreNullValues: "0"
        query: probe_success{instance=~".+:2049"}
        serverAddress: http://prometheus-operated.observability.svc.cluster.local:9090
        threshold: "1"
      type: prometheus
