---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: homepage-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ## Non Cluster resources
        HOMEPAGE_VAR_CLOUDFLARE_ACCOUNTID: "{{ .CLOUDFLARE_ACCOUNT_ID }}"
        HOMEPAGE_VAR_CLOUDFLARE_TUNNELID: "{{ .CLOUDFLARE_TUNNEL_ID }}"
        HOMEPAGE_VAR_CLOUDFLARE_API_TOKEN: "{{ .CLOUDFLARE_HOMEPAGE_TOKEN }}"
        ## Downloads
        #HOMEPAGE_VAR_BAZARR_API_KEY: "{{ .BAZARR_API_KEY }}"
        #HOMEPAGE_VAR_PROWLARR_API_KEY: "{{ .PROWLARR_API_KEY }}"
        #HOMEPAGE_VAR_RADARR_API_KEY: "{{ .RADARR_API_KEY }}"
        #HOMEPAGE_VAR_SABNZBD_API_KEY: "{{ .SABNZBD_API_KEY }}"
        HOMEPAGE_VAR_SONARR_API_KEY: "{{ .SONARR_API_KEY }}"
        HOMEPAGE_VAR_JELLYFIN_API_KEY: "{{ .JELLYFIN_HOMEPAGE_API_KEY }}"
        HOMEPAGE_VAR_GITEA_API_KEY: "{{ .GITEA_HOMEPAGE_API_KEY }}"
        HOMEPAGE_VAR_CALIBRE_USERNAME: "{{ .CALIBRE_USERNAME }}"
        HOMEPAGE_VAR_CALIBRE_PASSWORD: "{{ .CALIBRE_PASSWORD }}"
        #HOMEPAGE_VAR_IMMICH_API_KEY: "{{ .IMMICH_API_KEY }}"
        #HOMEPAGE_VAR_PAPERLESS_API_TOKEN: "{{ .PAPERLESS_API_TOKEN }}"
  dataFrom:
    - extract:
        key: cloudflare
    - extract:
        key: cloudflare-tunnel
    - extract:
       key: gitea
    - extract:
        key: jellyfin
    - extract:
        key: calibre
  #  - extract:
  #      key: paperless
  #  - extract:
  #      key: prowlarr
  #  - extract:
  #      key: qbittorrent
  #  - extract:
  #      key: radarr
  #  - extract:
  #      key: sabnzbd
    - extract:
        key: sonarr