---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slskd
spec:
  dataFrom:
    - extract:
        key: slskd
    - extract:
        key: protonvpn
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: slskd-secret
    template:
      data:
        SLSKD_API_KEY_HOMEPAGE: "{{ .SLSKD_API_KEY_HOMEPAGE }}"
        SLSKD_SLSK_PASSWORD: "{{ .SLSKD_SLSK_PASSWORD }}"
        SLSKD_SLSK_USERNAME: "{{ .SLSKD_SLSK_USERNAME }}"
        OPENVPN_USER: "{{ .OPENVPN_USER }}"
        OPENVPN_PASSWORD: "{{ .OPENVPN_PASSWORD }}"
