---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: radarr
  namespace: downloads
spec:
  components:
    - ../../../../components/ext-auth
    - ../../../../components/nfs-scaler
  dependsOn:
    - name: openebs
      namespace: openebs-system
    - name: cloudnative-pg-cluster
      namespace: dbms
    - name: onepassword-connect
      namespace: kube-system
    - name: authentik
      namespace: security
  interval: 1h
  path: ./kubernetes/apps/downloads/radarr/app
  postBuild:
    substitute:
      APP: radarr
      EXT_AUTH_APP: radarr
      EXT_AUTH_TARGET_NAME: radarr
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: downloads
  wait: false
