---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lidarr
spec:
  dataFrom:
    - extract:
        key: lidarr
    - extract:
        key: postgres
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: lidarr-secret
    template:
      data:
        # Postgres Init
        INIT_POSTGRES_DBNAME: "{{ .POSTGRES_DB }}"
        INIT_POSTGRES_HOST: postgres18.dbms.svc.cluster.local
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        # Lidarr
        LIDARR__AUTH__APIKEY: "{{ .LIDARR_API_KEY }}"
        LIDARR__POSTGRES__HOST: postgres18.dbms.svc.cluster.local
        LIDARR__POSTGRES__MAINDB: "{{ .POSTGRES_DB }}"
        LIDARR__POSTGRES__PASSWORD: "{{ .POSTGRES_PASS }}"
        LIDARR__POSTGRES__PORT: "5432"
        LIDARR__POSTGRES__USER: "{{ .POSTGRES_USER }}"
