apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:6WXu0MfDdVWqsA==,iv:FX+BriJYhyrgct58rNJoEbMz6Lsvio1WurMHYzTSQNA=,tag:uLB/EQx/MLUpg9Nefg2gwA==,type:str]
  S3_BACKUP_ENDPOINT: ENC[AES256_GCM,data:OzYSBULe3MmYARTx7iM89aG97hwRxA==,iv:qX5EaIFgVq21JHRGNeeCoUoB3sfRIB+V1SKtmFYBtKo=,tag:hFrbMGM+y8bRY3bFjEBBjQ==,type:str]
sops:
  age:
    - recipient: age1n3ql3mrczyduw5hxwcztsxxllfp7zwc6urxg4q6u20ras3whwuks8nqxvx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUFpMRlhVc1V0SjdIK2ky
        Rnhqd0lteXAvSm1zV29kZDlsczl2dVhXV2l3ClBEdHlXMVIrTzdMTHpsRW05UXdD
        OFpkN3lmUGppTlZWelFmdGVGTnpLUEEKLS0tIGJVdkp5OTloUFY1NTB0UzFNeDdQ
        bFZXY2NqOVN6bjJlRGdUaVNtNDlPY0UKvoNLI8cLRxDB9dc2rEEBYnYm/PkPkfJd
        4foMiJvuGDy5zyUmMjkyndLG/lFaontXvy8VIUTehI8/UXckVwIuOg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-02T09:12:03Z"
  mac: ENC[AES256_GCM,data:7IoH4vB5/RiuyNY7+jXW/jrZ6z26Ssg7lhGYft6wutlRQaWCWSpu6ggpGPh0JKBfDnslUiucduBbWtuZWgewWmbLfKdRd2kpvJ4EM1voNx5XLXt9908ewgGHtfXZv6C9j2/HeL+l/ooDj/60tRNVLuBxyui6qtCAUyee3Bkia8A=,iv:ZUsRiACaJtONIXop/9hER59Fa+hTn5lWd5QPQHb26hA=,tag:9yY+8fr6ksRtu3h5e85nog==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
