---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${OPENEBS_CLAIM:=${APP}}"
spec:
  accessModes: ["${OPENEBS_ACCESSMODES:=ReadWriteOnce}"]
  resources:
    requests:
      storage: "${OPENEBS_CAPACITY:=5Gi}"
  storageClassName: local-hostpath