---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lldap
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: lldap-secret
    template:
      data:
        # LLDAP
        LLDAP_JWT_SECRET: "{{ .LLDAP_JWT_SECRET }}"
        LLDAP_LDAP_USER_PASS: "{{ .LLDAP_LDAP_USER_PASS }}"
        LLDAP_LDAP_USER_EMAIL: "{{ .LLDAP_LDAP_USER_EMAIL }}"
        LLDAP_SERVER_KEY_SEED: "{{ .LLDAP_SERVER_KEY_SEED }}"
        LLDAP_LDAP_USER_DN: "{{ .LLDAP_LDAP_USER_DN }}"
        LLDAP_DATABASE_URL: "postgres://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASS }}@postgres-rw.dbms/lldap"
        LLDAP_SMTP_OPTIONS__SERVER: "{{ .LLDAP_SMTP_SERVER }}"
        LLDAP_SMTP_OPTIONS__FROM: "{{ .LLDAP_SMTP_FROM }}"
        LLDAP_SMTP_OPTIONS__REPLY_TO: "{{ .LLDAP_SMTP_REPLY_TO }}"
        LLDAP_SMTP_OPTIONS__PORT: "{{ .LLDAP_SMTP_PORT }}"
        LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET: "true"
        LLDAP_SMTP_OPTIONS__USER: ""
        LLDAP_SMTP_OPTIONS__PASSWORD: ""
        LLDAP_SMTP_OPTIONS__SMTP_ENCRYPTION: "NONE"
        # Postgres Init
        INIT_POSTGRES_DBNAME: lldap
        INIT_POSTGRES_HOST: postgres-rw.dbms
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: lldap
    - extract:
        key: postgres