---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/notification.toolkit.fluxcd.io/alert_v1beta3.json
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: alertmanager
spec:
  eventSeverity: error
  eventSources:
    - kind: FluxInstance
      name: "*"
    - kind: GitRepository
      name: "*"
    - kind: HelmRelease
      name: "*"
    - kind: HelmRepository
      name: "*"
    - kind: Kustomization
      name: "*"
    - kind: OCIRepository
      name: "*"
  exclusionList:
    - dial.*tcp.*timeout
    - error.*lookup.*github
    - waiting.*socket
  providerRef:
    name: alertmanager
  suspend: false
