---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: youtube-dl
  namespace: self-hosted
spec:
  interval: 1h
  path: ./kubernetes/apps/self-hosted/youtube-dl/app
  postBuild:
    substitute:
      APP: youtube-dl
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: self-hosted
  wait: false
